// <auto-generated />
using GeekBudget.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeekBudget.Migrations
{
    [DbContext(typeof(GeekBudgetContext))]
    [Migration("20170927124220_AddedTabsAndOperations")]
    partial class AddedTabsAndOperations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("GeekBudget.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeekBudget.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("Amount");

                    b.Property<string>("Comment");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("Date");

                    b.Property<int?>("FromId");

                    b.Property<int?>("ToId");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("GeekBudget.Models.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("Amount");

                    b.Property<string>("Currency");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("GeekBudget.Models.Operation", b =>
                {
                    b.HasOne("GeekBudget.Models.Tab", "From")
                        .WithMany("OperationsFrom")
                        .HasForeignKey("FromId");

                    b.HasOne("GeekBudget.Models.Tab", "To")
                        .WithMany("OperationsTo")
                        .HasForeignKey("ToId");
                });
#pragma warning restore 612, 618
        }
    }
}
